default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: jobify_db
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: jobify_development

test:
  <<: *default
  database: jobify_test

production:
  <<: *default
  database: jobify_production
  username: postgres
  password: postgres